# Generated by Django 2.2.3 on 2019-08-19 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20190817_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Contest')),
            ],
        ),
    ]
