# Generated by Django 2.2.3 on 2019-08-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='player1',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='player2',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='player3',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='player4',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='player5',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='player6',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='player7',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='player8',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
    ]
