# Generated by Django 2.2.3 on 2019-08-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_auto_20190819_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
