# Generated by Django 2.2.3 on 2019-08-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_delete_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='match1',
            field=models.CharField(default='0:0', max_length=250),
        ),
        migrations.AddField(
            model_name='contest',
            name='match2',
            field=models.CharField(default='0:0', max_length=250),
        ),
        migrations.AddField(
            model_name='contest',
            name='match3',
            field=models.CharField(default='0:0', max_length=250),
        ),
        migrations.AddField(
            model_name='contest',
            name='match4',
            field=models.CharField(default='0:0', max_length=250),
        ),
    ]
