# Generated by Django 2.2.3 on 2019-08-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_auto_20190820_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.CharField(default='0:0', max_length=250)),
                ('score2', models.CharField(default='0:0', max_length=250)),
                ('score3', models.CharField(default='0:0', max_length=250)),
                ('score4', models.CharField(default='0:0', max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='contest',
            name='match1',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='match2',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='match3',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='match4',
        ),
    ]
