# Generated by Django 2.2.3 on 2019-09-16 20:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
