# Generated by Django 2.2.3 on 2019-08-26 10:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0002_result'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tournament',
            new_name='Match',
        ),
    ]
