# Generated by Django 2.2.3 on 2019-08-24 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='host',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
